import { Outfit } from "next/font/google";
import "./globals.css";
import Navbar from "@/component/Navbar";
import Footer from "@/component/Footer";

const outfitFont = Outfit({
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${outfitFont.className}  h-full antialiased`}
    >
      <body>
        <Navbar/>
        <main className="max-w-7xl mx-auto">{children}</main>
        <Footer/>
        </body>
    </html>
  );
}


// 57/1-4, parveen pearl residence, east raja bazar, tejgaon thana, near panthopath signal, dhaka 1215